var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/exam-dashboard/test/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__060a0d92._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_c32d39bf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9cfc4081._.js")
R.c("server/chunks/ssr/node_modules_423e7141._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_0f1537ad._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_exam-dashboard_layout_jsx_778e152b._.js")
R.c("server/chunks/ssr/_next-internal_server_app_exam-dashboard_test_page_actions_73f7b364.js")
R.m(90144)
module.exports=R.m(90144).exports
